CREATE TABLE PUBLIC.MEMBER
(
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  email VARCHAR2(100) NOT NULL,
  password VARCHAR2(100) NOT NULL,
  name VARCHAR2(100) NOT NULL,
  registerDateTime DATETIME NOT NULL
);
CREATE UNIQUE INDEX "MEMBER_id_uindex" ON PUBLIC.MEMBER (id);
COMMENT ON TABLE PUBLIC.MEMBER IS '사용자';

CREATE TABLE PUBLIC.CONTENT
(
  contentNo INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  memberId VARCHAR2(100) NOT NULL,
  subject VARCHAR2(1000) NOT NULL,
  text BLOB NOT NULL,
  registerDateTime DATETIME NOT NULL,
  viewCount INT NOT NULL
);
CREATE UNIQUE INDEX "CONTENT_contentNo_uindex" ON PUBLIC.CONTENT (contentNo);
COMMENT ON TABLE PUBLIC.CONTENT IS '게시물';

/*
DROP PUBLIC.MEMBER
DROP PUBLIC.CONTENT
*/